# Phase 2: Generative AI & Prompt Engineering
## IBM HR Employee Attrition Dataset

# 1-Genrative AI model setup

Model Used:

We used LLaMA through Groq API to generate explanations and recommendations based on employee data.
 selected model was chosen due to:
- strong natural language generation capabilities
- ability to follow structured prompts
- fast response time suitable for iterative testing

In [11]:
# INSTALL DEPENDENCIES
%pip install groq python-dotenv

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: groq in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.2.0)
Requirement already satisfied: python-dotenv in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.2.2)
Requirement already satisfied: anyio<5,>=3.5.0 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from groq) (2.13.4)
Requirement already satisfied: sniffio in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from anyio<5,>=3.5.0->groq) (3.13)
Requirement already satisfied: certifi in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1,>=0.23.0->groq) (2026.4.22)
Requirement already satisfied: httpcore==1.* in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pydantic<3,>=1.9.0->groq) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\fatem\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [12]:
# IMPORTS libraries 
import os
import pandas as pd
import sys
sys.path.append("Generative_AI") # Tell Python where to find api_config.py 
from api_config import client          
import warnings
warnings.filterwarnings("ignore")

In [13]:
# Test connection to Groq
try:
    test = client.chat.completions.create(
        model="meta-llama/llama-4-scout-17b-16e-instruct",
        messages=[{"role": "user", "content": "Reply with OK only."}],
        max_completion_tokens=10 
    )
    print("Groq connected:", test.choices[0].message.content)

except Exception as e:
    print("Connection failed:", e)

Groq connected: OK

# 2- Prompt templates

### Template 1 – Basic Explanation (T1)

#### Intended Use Case
This template is designed to generate a simple explanation of the attrition prediction based on employee features. It is intended for quick understanding by non-technical users who need a basic interpretation of the prediction.

#### Design Rationale
The purpose of this template is to observe the model’s natural reasoning ability without enforcing structure or constraints. It helps establish a comparison point against more structured and advanced prompts.

#### Prompt Structure
You are an HR assistant.

Employee profile:
{features}

Prediction: Attrition = {prediction}

Explain why the employee may leave the company.

#### Example Input
Employee profile:
Age: 41  
BusinessTravel: Travel_Rarely  
Department: Sales  
DistanceFromHome: 1  
EducationField: Life Sciences  
JobRole: Sales Executive  
MonthlyIncome: 5993  
OverTime: Yes  
JobSatisfaction: 4  
WorkLifeBalance: 1  
YearsAtCompany: 6  

Prediction: Attrition = Yes

#### Example Output
Based on the employee profile, I would explain the prediction of Attrition = Yes as follows:

Although the employee has a relatively high JobSatisfaction rating of 4, which might suggest they are content with their job, there are other factors that could be contributing to their predicted attrition.

One potential reason is the employee's WorkLifeBalance rating of 1, which is very low. This suggests that the employee may be experiencing significant difficulties in balancing their work and personal life, which could lead to burnout and dissatisfaction.

Additionally, the employee does work overtime (OverTime: Yes), which could be a sign of an unsustainable workload or poor work-life balance.

It's also worth noting that the employee travels rarely (BusinessTravel: Travel_Rarely) and lives close to the workplace (DistanceFromHome: 1), which might not be a significant contributor to attrition.

However, with 6 years of service (YearsAtCompany: 6) and a relatively high MonthlyIncome (5993), it's possible that the employee may be looking for new challenges or opportunities that are not available in their current role.

Considering these factors, the prediction of Attrition = Yes may be driven by the employee's poor WorkLifeBalance and potential burnout, which could be outweighing their job satisfaction. Further discussion or analysis would be needed to confirm the reasons behind the prediction.



#### Assumptions & Limitations
Assumptions:

Simple explanations are sufficient for basic understanding
Users do not require detailed analysis

Limitations:

Lacks personalization
May produce vague or generic explanations
Does not provide actionable recommendations
Higher risk of hallucination due to weak constraints

### Template 2 – Structured HR Analysis (T2)

#### Intended Use Case
This template is designed to provide a structured and detailed HR analysis of the attrition prediction, including key factors, risks, and recommended actions.

#### Design Rationale
This template introduces a structured format to guide the model toward generating more organized and actionable insights. By explicitly requesting key factors, risks, and recommendations, the output becomes more useful for decision-making compared to a basic explanation.

#### Prompt Structure
You are an HR expert analyzing employee attrition risk.

Employee profile:
{features}

Prediction: Attrition = {prediction}

Provide:
1. Key factors contributing to this prediction
2. Risks associated with this employee leaving
3. Recommended actions to retain this employee

Use clear bullet points.

#### Example Input
Employee profile:
Age: 37  
BusinessTravel: Travel_Rarely  
Department: Research & Development  
DistanceFromHome: 2  
EducationField: Other  
JobRole: Laboratory Technician  
MonthlyIncome: 2090  
OverTime: Yes  
JobSatisfaction: 2  
WorkLifeBalance: 3  
YearsAtCompany: 0  

Prediction: Attrition = Yes

#### Example Output
Based on the employee profile, here is the analysis:

**1. Main factors behind this prediction:**

* **Low JobSatisfaction (2)**: The employee is not satisfied with their job, which is a strong indicator of attrition risk.
* **Low MonthlyIncome (2090)**: The employee's income is relatively low, which may lead to dissatisfaction and motivation to look for better-paying opportunities.
* **OverTime (Yes)**: The employee is required to work overtime, which can lead to burnout and negatively impact work-life balance.
* **Young tenure (YearsAtCompany: 0)**: The employee is new to the company, which makes them more vulnerable to attrition risk.

**2. Possible risk level:**
* **High Risk**: The combination of low job satisfaction, relatively low income, and overtime requirements suggests a high risk of attrition.

**3. Recommended HR actions:**
* **Retention interview**: Conduct a thorough interview with the employee to understand the root causes of their dissatisfaction and address their concerns.
* **Salary review**: Consider a salary adjustment to bring the employee's income more in line with industry standards.
* **Work-life balance improvement**: Explore options to reduce or manage overtime requirements to improve the employee's work-life balance.
* **Job enrichment**: Provide opportunities for growth and development within the Laboratory Technician role or consider lateral moves within the Research & Development department.
* **Onboarding and support**: Ensure the employee receives comprehensive onboarding and ongoing support to help them settle into their new role and feel more engaged with the company.


#### Assumptions & Limitations
Assumptions:

Structured output improves readability
HR users prefer organized insights

Limitations:

Still not deeply personalized
Recommendations are missing
May oversimplify relationships between features
Depends on model interpretation

### Template 3 – Manager-Friendly Explanation (T3)

#### Intended Use Case
This template is designed to generate a simple and clear explanation for non-technical managers who need to understand attrition predictions without technical details.

#### Design Rationale
This template focuses on readability and clarity by simplifying the explanation and avoiding technical language. It helps evaluate how well the model communicates insights to non-expert stakeholders.

#### Prompt Structure
You are explaining the attrition prediction to a non-technical manager.

Employee profile:
{features}

Prediction: Attrition = {prediction}

Explain in simple language:
- Why this employee may stay or leave
- What the company should do next

Avoid technical terms.

#### Example Input
Employee profile:
Age: 49  
BusinessTravel: Travel_Frequently  
Department: Research & Development  
DistanceFromHome: 8  
EducationField: Life Sciences  
JobRole: Research Scientist  
MonthlyIncome: 5130  
OverTime: No  
JobSatisfaction: 3  
WorkLifeBalance: 3  
YearsAtCompany: 10  

Prediction: Attrition = No

#### Example Output
Let me break down the prediction in simple terms:

**Why this employee may stay:**
Our analysis suggests that this employee is likely to stay with the company. Here are a few reasons why:

* They have been with the company for 10 years, which indicates a level of loyalty and commitment.
* They have a relatively high monthly income of $5130, which suggests that they are fairly compensated for their work.
* Although their job satisfaction and work-life balance are only average (rated 3 out of 5), these factors aren't strong indicators of attrition in this case.

**Why this employee may leave (but we're not predicting that):**
While we're not predicting attrition, there are a few factors that could potentially contribute to turnover:

* The employee travels frequently for business, which can be stressful and impact work-life balance.
* They are 49 years old, which is an age where some employees might start thinking about retirement or exploring new opportunities.

**What the company should do next:**
Based on our analysis, here are some recommendations:

* Continue to monitor the employee's job satisfaction and work-life balance to ensure that these factors don't become a concern.
* Consider offering opportunities for growth and development within the Research & Development department to keep the employee engaged and motivated.
* Since the employee travels frequently, consider offering support or resources to help them manage their work-life balance while on the road.

Overall, our prediction suggests that this employee is likely to stay with the company, but it's always important to stay proactive and address any potential concerns before they become major issues.

#### Assumptions & Limitations
Assumptions:

Managers prefer short, high-level insights
Key factors are sufficient for decisions

Limitations:

Lacks depth and detailed reasoning
No personalized recommendations
May omit important contextual factors
Less informative for analysis purposes

### Template 4 – Personalized Retention Advice (T4)

#### Intended Use Case
This template is designed to generate personalized and actionable retention advice based on individual employee characteristics.

#### Design Rationale
This template aims to produce highly relevant and personalized outputs by focusing on individual features and requiring practical recommendations. It is expected to outperform other templates in relevance and usefulness.

#### Prompt Structure
You are an HR consultant providing personalized advice.

Employee profile:
{features}

Prediction: Attrition = {prediction}

Based only on the provided employee data:
- Identify the most important individual risk factors
- Explain how they relate to attrition
- Provide practical and personalized recommendations
- Avoid unsupported assumptions

Be specific and realistic.

#### Example Input
Employee profile:
Age: 27  
BusinessTravel: Travel_Rarely  
Department: Research & Development  
DistanceFromHome: 2  
EducationField: Medical  
JobRole: Research Scientist  
MonthlyIncome: 3468  
OverTime: Yes  
JobSatisfaction: 2  
WorkLifeBalance: 3  
YearsAtCompany: 2  

Prediction: Attrition = Yes


Prediction: Attrition = Yes

#### Example Output
Based on the provided employee data, I'll analyze the individual risk factors contributing to the predicted attrition.

**Most important individual risk factors:**

1. **Low JobSatisfaction (2)**: This is a significant risk factor, as employees with low job satisfaction are more likely to leave the organization. A score of 2 indicates that the employee is not satisfied with their job, which could be due to various reasons such as lack of challenges, poor work environment, or limited growth opportunities.
2. **High OverTime (Yes)**: Working overtime can lead to burnout, which can contribute to attrition. If the employee is consistently working overtime, it may indicate an unsustainable workload or poor work-life balance.
3. **Low WorkLifeBalance (3)**: Although the score is not extremely low, it still indicates that the employee may be struggling to balance their work and personal life. This can lead to dissatisfaction and increased likelihood of attrition.

**Relationship to attrition:**

These risk factors are interrelated and can create a vicious cycle. Low job satisfaction can lead to increased overtime as the employee tries to cope with their dissatisfaction or make up for perceived shortcomings. This, in turn, can further exacerbate work-life balance issues, leading to increased stress and burnout. If left unaddressed, these factors can ultimately contribute to the employee's decision to leave the organization.

**Practical and personalized recommendations:**

1. **Conduct a one-on-one meeting**: Schedule a meeting with the employee to discuss their job satisfaction concerns. Listen actively to their feedback and concerns, and take notes on specific issues they raise.
2. **Explore workload and overtime**: Discuss the employee's workload and overtime requirements. Identify potential areas where tasks can be delegated or adjusted to


#### Assumptions & Limitations
Assumptions:

Employee features accurately reflect real conditions
Personalized advice improves retention outcomes
Model prediction is reasonably reliable

Limitations:

Limited to available dataset features 
May oversimplify complex human behavior
Recommendations are generic HR strategies, not guaranteed solutions
Still dependent on LLM reasoning, may introduce subtle bias

# 3- Implementation & API Integration Code

The Generative AI model is accessed via A custom function (get_ai_response) to send the prompt to the model and retrieve the generated response.

The API key used to access the model is stored securely in  environment variables to prevent exposure.

In [ ]:
MODEL_NAME = "meta-llama/llama-4-scout-17b-16e-instruct"
# Send prompt to Groq API and return the model's text response
def get_ai_response(prompt, max_tokens=350):
    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[{"role": "user", "content": prompt}], # message format
        max_completion_tokens=max_tokens, # limit response length
        temperature=0.3  # low = less random, more consistent
    )
    return response.choices[0].message.content

# 4- Testing 

to evaluate the prompt templates
- Three employee records were randomly selected from the dataset
- Each record was tested using all four prompt templates
- This resulted in 12 generated outputs (4 templates × 3 cases)

In [15]:


templates = {
    "T1_Basic_Explanation": """
You are an HR assistant.

Employee profile:
{features}

Prediction: Attrition = {prediction}

Explain why the employee may be predicted as {prediction}.
Keep the explanation clear and relevant to the given employee data.
""",

    "T2_Structured_HR_Analysis": """
You are an HR expert analyzing employee attrition risk.

Employee profile:
{features}

Prediction: Attrition = {prediction}

Provide:
1. Main factors behind this prediction
2. Possible risk level
3. Recommended HR actions

Use clear bullet points.
""",

    "T3_Manager_Friendly_Explanation": """
You are explaining the attrition prediction to a non-technical manager.

Employee profile:
{features}

Prediction: Attrition = {prediction}

Explain in simple language:
- Why this employee may stay or leave
- What the company should do next

Avoid machine learning jargon.
""",

    "T4_Personalized_Retention_Advice": """
You are an HR consultant giving personalized retention advice.

Employee profile:
{features}

Prediction: Attrition = {prediction}

Based only on the provided employee data:
- Identify the most important individual risk factors
- Explain how they relate to attrition
- Give practical and personalized recommendations
- Avoid making unsupported assumptions

Be specific, realistic, and professional.
"""
}

In [16]:
#choose 3 rows from the dataset randomly
selected_cols = [
    "Age",
    "BusinessTravel",
    "Department",
    "DistanceFromHome",
    "EducationField",
    "JobRole",
    "MonthlyIncome",
    "OverTime",
    "JobSatisfaction",
    "WorkLifeBalance",
    "YearsAtCompany"
]

df = pd.read_csv("Dataset/Raw_Kaggle_HR_Employee_Attrition_data.csv")

sample_df = df.sample(n=3, random_state=42)

def row_to_features(row):
    return "\n".join([f"{col}: {row[col]}" for col in selected_cols])

test_cases = []

for i, row in sample_df.iterrows():
    test_cases.append({
        "case_id": f"Case {len(test_cases)+1}",
        "prediction": row["Attrition"],
        "features": row_to_features(row)
    })

test_cases

[{'case_id': 'Case 1',
  'prediction': 'No',
  'features': 'Age: 28\nBusinessTravel: Travel_Rarely\nDepartment: Sales\nDistanceFromHome: 5\nEducationField: Medical\nJobRole: Sales Executive\nMonthlyIncome: 8463\nOverTime: No\nJobSatisfaction: 1\nWorkLifeBalance: 3\nYearsAtCompany: 5'},
 {'case_id': 'Case 2',
  'prediction': 'No',
  'features': 'Age: 53\nBusinessTravel: Travel_Rarely\nDepartment: Research & Development\nDistanceFromHome: 13\nEducationField: Medical\nJobRole: Manufacturing Director\nMonthlyIncome: 4450\nOverTime: No\nJobSatisfaction: 1\nWorkLifeBalance: 3\nYearsAtCompany: 4'},
 {'case_id': 'Case 3',
  'prediction': 'Yes',
  'features': 'Age: 24\nBusinessTravel: Travel_Rarely\nDepartment: Human Resources\nDistanceFromHome: 22\nEducationField: Human Resources\nJobRole: Human Resources\nMonthlyIncome: 1555\nOverTime: No\nJobSatisfaction: 3\nWorkLifeBalance: 3\nYearsAtCompany: 1'}]

In [17]:
#get results
results = []


for template_name, template_text in templates.items():
    for case in test_cases:
        prompt = template_text.format(
            features=case["features"],
            prediction=case["prediction"]
        )

        output = get_ai_response(prompt,max_tokens=700)

        results.append({
            "Template": template_name,
            "Case": case["case_id"],
            "Prediction": case["prediction"],
            "Output": output,
            "Word_Count": len(output.split()),
        })

results_df = pd.DataFrame(results)
results_df

,Template,Case,Prediction,Output,Word_Count
0,T1_Basic_Explanation,Case 1,No,"Based on the provided employee profile, the pr...",353
1,T1_Basic_Explanation,Case 2,No,"Based on the provided employee profile, the pr...",384
2,T1_Basic_Explanation,Case 3,Yes,"Based on the employee profile, I would explain...",215
3,T2_Structured_HR_Analysis,Case 1,No,"Based on the provided employee profile, here i...",299
4,T2_Structured_HR_Analysis,Case 2,No,"Based on the employee profile, here are my ana...",318
5,T2_Structured_HR_Analysis,Case 3,Yes,"Based on the employee profile, here is the ana...",318
6,T3_Manager_Friendly_Explanation,Case 1,No,Let me break it down in simple terms:\n\n**Why...,311
7,T3_Manager_Friendly_Explanation,Case 2,No,Let me break it down in simple terms:\n\n**Why...,350
8,T3_Manager_Friendly_Explanation,Case 3,Yes,Let me break it down in simple terms:\n\n**Why...,319
9,T4_Personalized_Retention_Advice,Case 1,No,"Based on the provided employee data, I'll anal...",367
10,T4_Personalized_Retention_Advice,Case 2,No,"Based on the provided employee data, I'll anal...",379
11,T4_Personalized_Retention_Advice,Case 3,Yes,"Based on the provided employee data, I'll anal...",354

In [18]:
#save results

results_df.to_csv(
    "Generative_AI/example_outputs/Generative_AI_Output_Comparison.csv",
    index=False
)

In [19]:
%pip install textstat

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: textstat in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.7.13)
Requirement already satisfied: pyphen in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textstat) (0.17.2)
Requirement already satisfied: nltk in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textstat) (3.9.4)
Requirement already satisfied: setuptools in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textstat) (82.0.0)
Requirement already satisfied: click in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nltk->textstat) (8.3.3)
Requirement already satisfied: joblib in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nltk->textstat) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nltk->textstat) (2026.4.4)
Requirement already satisfied: tqdm in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nltk->textstat) (4.67.3)
Requirement already satisfied: colorama in C:\Users\fatem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from click->nltk->textstat) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\fatem\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [21]:
import pandas as pd
df = pd.read_csv("Generative_AI/example_outputs/Generative_AI_Output_Comparison.csv")

from IPython.display import Markdown, display

for _, row in df.iterrows():
    display(Markdown(f"""
---
### {row['Template']} — {row['Case']} | Prediction: {row['Prediction']}

{row['Output']}
"""))

---
### T1_Basic_Explanation — Case 1 | Prediction: No

Based on the provided employee profile, the prediction of Attrition = No can be explained as follows:

1. **YearsAtCompany: 5**: The employee has been with the company for 5 years, which indicates a certain level of job satisfaction and stability. Longevity with a company often suggests that an employee is engaged and committed to their role.

2. **MonthlyIncome: 8463**: The employee's monthly income is relatively high, which could contribute to job satisfaction and reduce the likelihood of seeking new opportunities elsewhere.

3. **JobRole: Sales Executive and Department: Sales**: While sales roles can be high-pressure, the fact that the employee has remained in this role for 5 years suggests they are either well-suited to it or have found ways to manage its demands effectively.

4. **OverTime: No**: The absence of overtime might indicate a manageable workload, which can contribute to a better work-life balance and job satisfaction.

5. **WorkLifeBalance: 3**: While not the highest score, a WorkLifeBalance rating of 3 suggests that the employee is able to manage their work and personal life fairly well, which can reduce the likelihood of attrition.

6. **DistanceFromHome: 5**: A short distance from home can make commuting easier and less stressful, potentially contributing to job satisfaction.

7. **BusinessTravel: Travel_Rarely**: Rare business travel could mean less disruption to the employee's personal life and less stress related to travel, which might contribute to job satisfaction.

8. **EducationField: Medical and JobRole: Sales Executive**: While there's a field switch from Medical to Sales, the employee has adapted to this change for 5 years, suggesting either a strong interest in sales or effective support from the company in their role transition.

9. **JobSatisfaction: 1**: Although the job satisfaction rating is low, it seems to be an outlier given the other positive indicators (long tenure, manageable work-life balance, etc.). It's possible that while the employee isn't highly satisfied, they are not actively seeking to leave.

Considering these factors, the prediction of Attrition = No seems reasonable. The employee's long tenure, relatively high income, manageable work-life balance, and lack of excessive work demands (e.g., overtime) likely contribute to a lower inclination to leave the company.

---
### T1_Basic_Explanation — Case 2 | Prediction: No

Based on the provided employee profile, the prediction of "Attrition = No" suggests that this employee is likely to stay with the company. Here are some key factors that may contribute to this prediction:

1. **Job Role and Seniority**: As a 53-year-old Manufacturing Director in the Research & Development department, this employee holds a senior position with significant responsibility. Typically, employees in senior roles may feel more invested in the organization and have more reasons to stay.

2. **Years at Company**: With 4 years of service, this employee has already demonstrated a level of commitment to the company. The fact that they have been with the organization for several years suggests they may have developed strong professional and possibly personal ties.

3. **Monthly Income**: The employee's monthly income of 4450 is a tangible factor. While we don't have a basis for comparison, being a director, this income might be considered satisfactory or competitive, potentially reducing the incentive to look for another job.

4. **Job Satisfaction and Work-Life Balance**: Although the Job Satisfaction is rated at 1 (which might indicate low satisfaction), the Work-Life Balance is rated at 3, which could suggest a moderate level of satisfaction with their personal life outside of work. The combination of these ratings might indicate that while there are areas for improvement, they are not extreme enough to strongly predict attrition.

5. **Business Travel and Distance from Home**: The employee travels rarely for business and lives 13 units of distance from home. This could imply a stable routine and minimal disruption to their personal life, which might contribute to job satisfaction and reduce the likelihood of leaving.

6. **Education Field and Job Role Alignment**: With an education field in Medical and a role as a Manufacturing Director, there might be a direct application of their knowledge, providing a sense of relevance and fulfillment in their job.

7. **No Overtime**: The fact that the employee does not work overtime could indicate a manageable workload or a healthy boundary between work and personal life, which could contribute to their decision to stay.

Considering these factors, the prediction of "Attrition = No" seems to be based on a combination of job security, seniority, satisfactory income, moderate work-life balance, and possibly a sense of fulfillment and engagement with their role and the company.

---
### T1_Basic_Explanation — Case 3 | Prediction: Yes

Based on the employee profile, I would explain the prediction of Attrition = Yes as follows:

The employee is 24 years old and has been with the company for only 1 year. Despite being in the Human Resources department, which aligns with their education field, their job satisfaction and work-life balance are rated as 3, which is a neutral/middle rating. This suggests that the employee may not be extremely happy or fulfilled in their role.

Additionally, the employee's monthly income is $1555, which may not be competitive for someone with 1 year of experience in the Human Resources field. The fact that they travel rarely and have a moderate distance from home (22) may not be significant contributors to their job satisfaction.

The prediction of Attrition = Yes may be driven by the employee's relatively low job satisfaction and work-life balance ratings, which could indicate that they are not engaged or motivated in their role. Furthermore, being young and relatively new to the company, they may be more likely to explore other job opportunities that better align with their career goals and provide more satisfaction.

Overall, the prediction suggests that the employee may be at risk of leaving the company due to a lack of fulfillment and potentially limited growth opportunities in their current role.

---
### T2_Structured_HR_Analysis — Case 1 | Prediction: No

Based on the provided employee profile, here is the analysis:

**1. Main factors behind the prediction (Attrition = No)**

* **JobSatisfaction: 1** (very dissatisfied, but surprisingly, the model predicts no attrition - this might indicate other factors are at play)
* **YearsAtCompany: 5** (employee has been with the company for a relatively long time, indicating some level of commitment or stability)
* **MonthlyIncome: 8463** (relatively high income, which could be a motivator to stay)
* **Department: Sales** and **JobRole: Sales Executive** (sales roles can be challenging, but the employee has been in this role for 5 years, suggesting some level of comfort or success)

**2. Possible risk level**

* Despite the prediction of no attrition, there are some red flags:
	+ Low **JobSatisfaction** (1) indicates a potential issue that should be addressed
	+ **WorkLifeBalance: 3** (neutral) might not be ideal, as it doesn't indicate a high level of satisfaction
* Risk level: **Moderate** (there are some concerns, but the employee's long tenure and relatively high income might mitigate the risk)

**3. Recommended HR actions**

* **Investigate JobSatisfaction**: understand the root causes of the employee's dissatisfaction and address them
* **Conduct a stay interview**: discuss the employee's goals, aspirations, and concerns to better understand their perspective
* **Review and adjust compensation and benefits**: ensure the employee's income and benefits are competitive and aligned with their role and industry
* **Offer development opportunities**: provide training, mentorship, or new challenges to help the employee grow and feel engaged in their role
* **Monitor WorkLifeBalance**: check in with the employee to ensure they have a healthy balance between work and personal life

By taking proactive steps to address the employee's concerns and provide support, HR can help mitigate the risk of attrition and ensure the employee remains engaged and committed to the company.

---
### T2_Structured_HR_Analysis — Case 2 | Prediction: No

Based on the employee profile, here are my analysis and recommendations:

**1. Main factors behind the prediction that Attrition = No:**

* **JobRole stability**: As a Manufacturing Director, the employee holds a senior leadership position, which often comes with a sense of stability and responsibility.
* **Reasonable income**: The monthly income of $4450 is a relatively good compensation package, which can contribute to job satisfaction and reduce attrition risk.
* **Long tenure**: With 4 years at the company, the employee has established roots and is likely to have built strong relationships with colleagues and management.
* **Moderate work-life balance**: A score of 3 on WorkLifeBalance suggests that the employee is able to manage their work and personal life reasonably well, reducing the likelihood of burnout.

**2. Possible risk level:**
Despite the prediction that Attrition = No, there are still some potential risk factors to consider:

* **Low JobSatisfaction**: A score of 1 on JobSatisfaction is a concern, as it may indicate that the employee is not engaged or motivated in their role.
* **Limited travel**: While Travel_Rarely may be a benefit for some employees, it could also lead to feelings of stagnation or boredom for others.

Risk level: **Moderate** (there are some potential concerns, but overall, the employee seems stable)

**3. Recommended HR actions:**

* **Investigate JobSatisfaction**: Schedule a meeting with the employee to discuss their job satisfaction and understand the root causes of their low score. Is it related to their role, responsibilities, or something else?
* **Explore growth opportunities**: Consider providing training, mentorship, or new challenges to help the employee grow professionally and feel more engaged in their role.
* **Regular check-ins**: Schedule regular check-ins with the employee to monitor their job satisfaction and work-life balance, and address any concerns promptly.
* **Recognition and rewards**: Consider recognizing and rewarding the employee for their contributions to the company, which can help boost their job satisfaction and motivation.

---
### T2_Structured_HR_Analysis — Case 3 | Prediction: Yes

Based on the employee profile, here is the analysis:

**1. Main factors behind this prediction:**

* **Low JobSatisfaction (3) and WorkLifeBalance (3)**: These scores indicate that the employee is not satisfied with their job and struggles to balance their work and personal life, which are common precursors to attrition.
* **Young age (24) and relatively low MonthlyIncome (1555)**: Younger employees with lower salaries may be more likely to explore new opportunities, especially if they feel undervalued or unfulfilled in their current role.
* **Short tenure (YearsAtCompany = 1)**: Employees in their first year with a company are generally more likely to leave than those who have been with the organization longer.

**2. Possible risk level:**
* **Moderate to High Risk**: Given the combination of factors mentioned above, there is a notable risk that this employee may choose to leave the company.

**3. Recommended HR actions:**

* **Conduct a confidential exit interview (or a check-in conversation)**: Schedule a meeting with the employee to discuss their job satisfaction, work-life balance, and any concerns they may have. This can help identify specific issues and provide an opportunity to address them.
* **Review and adjust compensation**: Consider adjusting the employee's salary to be more competitive with industry standards, or provide additional benefits that may improve their overall compensation package.
* **Provide opportunities for growth and development**: As the employee is in the Human Resources department and has an EducationField in Human Resources, consider providing training, mentorship, or opportunities for advancement within the department to increase job satisfaction and engagement.
* **Monitor and address work-life balance**: Encourage the employee to take breaks, use their paid time off, and maintain a healthy work-life balance. This may involve discussing flexible work arrangements or providing resources to support work-life balance.
* **Regular check-ins**: Schedule regular check-ins with the employee to monitor their job satisfaction and address any concerns they may have before they become major issues.

---
### T3_Manager_Friendly_Explanation — Case 1 | Prediction: No

Let me break it down in simple terms:

**Why this employee may stay or leave:**

Based on the information we have about this employee, our prediction suggests that they are likely to stay with the company (Attrition = No). Here are some key factors that contribute to this prediction:

* They are relatively young (28) and have a good income (₹8463 per month).
* They are a Sales Executive, which is a role that often has a lot of interaction with customers and can be engaging.
* They have a good job satisfaction rating (1, which we assume is a positive rating).
* They rarely travel for business, which can be a plus for work-life balance.

However, there are also some potential concerns:

* They have been with the company for 5 years, which can sometimes lead to complacency or a desire for new challenges.
* Their work-life balance rating is 3, which is neutral - it's not great, but not terrible either.

**What the company should do next:**

To keep this employee engaged and motivated, here are some suggestions:

* **Regular check-ins**: Have a conversation with them to understand their goals, aspirations, and any concerns they may have. This will help identify areas where the company can support them.
* **Growth opportunities**: Explore possibilities for growth or new challenges within the Sales department or elsewhere in the company. This could be a new project, a promotion, or additional responsibilities.
* **Wellness initiatives**: Consider ways to improve work-life balance, such as flexible working hours, wellness programs, or employee benefits that support their personal and professional well-being.
* **Feedback and recognition**: Continue to provide regular feedback and recognition for their achievements, which can help boost job satisfaction and motivation.

By taking these steps, the company can proactively work to retain this valuable employee and help them continue to thrive in their role.

---
### T3_Manager_Friendly_Explanation — Case 2 | Prediction: No

Let me break it down in simple terms:

**Why this employee may stay or leave:**

Based on the information we have about this employee, our prediction is that they are likely to stay with the company (Attrition = No). Here are some key factors that contribute to this prediction:

* They are 53 years old and have been with the company for 4 years, which suggests they have a certain level of stability and may be less likely to look for a new job.
* They have a relatively high monthly income of $4450, which could make them more satisfied with their job and less likely to leave.
* They have a low level of job satisfaction (rated 1), but surprisingly, this doesn't seem to be a major concern for them. It's possible that they have found ways to cope with this or have other priorities that keep them engaged.
* They have a good work-life balance (rated 3), which is important for their overall well-being and may reduce their desire to leave.

**What the company should do next:**

While our prediction suggests that this employee is likely to stay, there are still some potential concerns that the company should address:

* Their low job satisfaction rating is a red flag. The company should consider having a conversation with this employee to understand what's driving their dissatisfaction and see if there are any changes that can be made to improve their experience.
* Given their role as a Manufacturing Director, the company may want to consider providing additional support or resources to help them feel more engaged and motivated in their job.
* Since they travel rarely, the company could explore opportunities for them to take on new challenges or projects that could help keep them engaged and interested in their work.

Overall, while this employee is likely to stay with the company, it's still important to check in with them regularly to ensure that their concerns are heard and addressed. By doing so, the company can help reduce the risk of attrition and create a more positive work environment.

---
### T3_Manager_Friendly_Explanation — Case 3 | Prediction: Yes

Let me break it down in simple terms:

**Why this employee may leave:**
Our analysis suggests that this 24-year-old Human Resources employee may be at risk of leaving the company. Although they've only been with us for a year, their profile indicates some potential concerns. Specifically, their job satisfaction and work-life balance are rated as average (3 out of a certain scale). This could indicate that they're not entirely happy with their job or work environment. Additionally, their monthly income is relatively low compared to what we know about our employees.

**Why this employee may stay:**
On the other hand, this employee works in the Human Resources department, which aligns with their education field and job role. This could suggest that they're in a field they're interested in and may have a sense of purpose. They also don't travel frequently for business and are relatively close to home, which could be a plus.

**What the company should do next:**
Given these insights, we recommend that the company takes proactive steps to engage with this employee and address potential concerns. Here are some suggestions:

1. **Check-in with the employee:** Have a conversation with them to understand their concerns and see if there's anything we can do to improve their job satisfaction and work-life balance.
2. **Explore growth opportunities:** Since they're in a field they're interested in, we could explore opportunities for growth and development within the Human Resources department. This might help them feel more engaged and motivated.
3. **Review compensation:** Consider reviewing their monthly income to ensure it's competitive and fair. This could help alleviate any financial concerns they may have.
4. **Offer support:** Make sure they know that support is available if they need it, whether that's related to work-life balance or professional development.

By taking these steps, we can try to address any concerns this employee may have and reduce the likelihood of them leaving the company.

---
### T4_Personalized_Retention_Advice — Case 1 | Prediction: No

Based on the provided employee data, I'll analyze the individual risk factors, their relation to attrition, and offer practical recommendations.

**Most important individual risk factors:**

1. **Low JobSatisfaction (1)**: This is a significant risk factor, as an employee with low job satisfaction is more likely to consider leaving the organization.
2. **YearsAtCompany (5)**: While having an employee for 5 years can be a positive aspect, it can also indicate that the employee has been with the company for a moderate amount of time, potentially leading to complacency or a desire for new challenges.

**Relation to attrition:**

* Low JobSatisfaction can lead to attrition as employees who are unhappy with their job are more likely to seek new opportunities that better align with their expectations and needs.
* An employee who has been with the company for 5 years may start to feel stagnant or ready for a change, increasing the likelihood of attrition if their needs are not met.

**Practical and personalized recommendations:**

1. **Conduct a thorough conversation**: Schedule a meeting with the Sales Executive to discuss their job satisfaction concerns. Ask open-ended questions to understand the root causes of their dissatisfaction, such as:
	* What are your most significant pain points in your current role?
	* What are your short-term and long-term career goals?
	* What would make you more engaged and motivated in your job?
2. **Explore growth opportunities**: Based on the conversation, identify potential growth opportunities within the Sales department or other areas of the company that align with the employee's interests, skills, and career goals. This could include:
	* Additional training or mentorship programs
	* New project assignments or leadership roles
	* Cross-functional collaboration opportunities
3. **Recognize and reward**: Consider recognizing and rewarding the Sales Executive for their contributions to the company over the past 5 years. This could be a simple gesture, such as a bonus or a public acknowledgement of their dedication.
4. **Regular check-ins**: Schedule regular check-ins (e.g., quarterly) to monitor the employee's job satisfaction and address any concerns promptly.

By addressing the Sales Executive's job satisfaction concerns and providing growth opportunities, you can reduce the risk of attrition and help them feel more engaged and motivated in their role.

---
### T4_Personalized_Retention_Advice — Case 2 | Prediction: No

Based on the provided employee data, I'll analyze the individual risk factors, their relation to attrition, and provide personalized recommendations.

**Most important individual risk factors:**

1. **JobSatisfaction: 1** (very low satisfaction)
2. **YearsAtCompany: 4** (relatively short tenure, but not extremely low)
3. **DistanceFromHome: 13** ( moderate distance, potentially impacting work-life balance)

**Relation to attrition:**

1. **Low JobSatisfaction**: A JobSatisfaction score of 1 is a significant risk factor for attrition. When employees are unhappy with their job, they are more likely to seek new opportunities elsewhere.
2. **Short tenure**: Although 4 years is not a short tenure, it is still a relatively early stage in an employee's career with a company. If an employee is not satisfied, they may be more likely to leave before investing more time and energy.
3. **DistanceFromHome**: A distance of 13 units from home may cause difficulties in commuting, impacting work-life balance. This could contribute to dissatisfaction and potentially increase the likelihood of attrition.

**Practical and personalized recommendations:**

1. **Conduct a thorough conversation**: Schedule a meeting with the Manufacturing Director to discuss their job satisfaction concerns. Listen actively to their feedback, and identify specific areas causing dissatisfaction.
2. **Address concerns and improve job satisfaction**: Based on the conversation, develop a plan to address the employee's concerns. This might involve:
	* Providing additional resources or support to improve their work experience.
	* Exploring opportunities for growth and development within the Research & Development department.
	* Adjusting their workload or responsibilities to better align with their interests and skills.
3. **Explore flexible work arrangements**: Consider offering flexible work arrangements, such as telecommuting or flexible hours, to help alleviate commuting difficulties and improve work-life balance.
4. **Recognition and engagement**: Regularly recognize and appreciate the employee's contributions to the organization. Engage them in discussions about the company's goals, vision, and future plans to help them feel more connected and invested.

**Additional suggestions:**

* Monitor the employee's progress and job satisfaction closely over the next 6-12 months.
* Consider a mid-term review (e.g., 6 months) to assess the effectiveness of the implemented changes and make adjustments as needed.

By addressing the employee's concerns, improving job satisfaction, and offering support, the organization can reduce the risk of attrition and help the Manufacturing Director feel more engaged and committed to their role.

---
### T4_Personalized_Retention_Advice — Case 3 | Prediction: Yes

Based on the provided employee data, I'll analyze the individual risk factors contributing to the predicted attrition.

**Most important individual risk factors:**

1. **JobSatisfaction: 3** (Neutral satisfaction level)
2. **WorkLifeBalance: 3** (Neutral work-life balance)
3. **DistanceFromHome: 22** (Significant distance from home)
4. **YearsAtCompany: 1** (Relatively short tenure)

**Relationship to attrition:**

* **JobSatisfaction: 3**: A neutral satisfaction level indicates that the employee is not strongly engaged or dissatisfied. However, it suggests a lack of enthusiasm or excitement about their job, which can lead to a higher likelihood of exploring alternative opportunities.
* **WorkLifeBalance: 3**: A neutral work-life balance may indicate that the employee is struggling to manage their personal and professional responsibilities. This can lead to burnout, decreased motivation, and increased turnover.
* **DistanceFromHome: 22**: A significant distance from home can lead to commuting stress, decreased work-life balance, and increased fatigue. This can negatively impact job satisfaction and increase the likelihood of attrition.
* **YearsAtCompany: 1**: With only 1 year at the company, the employee is still in the early stages of their tenure. Research suggests that employees are more likely to leave organizations during the first year of employment.

**Practical and personalized recommendations:**

1. **Regular check-ins**: Schedule regular 1-on-1 meetings with the employee to discuss their job satisfaction, work-life balance, and any challenges they're facing. This will help identify potential issues before they become major concerns.
2. **Explore flexible work arrangements**: Consider offering flexible work arrangements, such as telecommuting or flexible hours, to help alleviate commuting stress and improve work-life balance.
3. **Professional development opportunities**: Provide opportunities for professional growth and development within the Human Resources department. This can help increase job satisfaction and engagement.
4. **Recognition and feedback**: Regularly recognize and provide constructive feedback on the employee's performance. This can help boost job satisfaction and motivation.
5. **Employee wellness initiatives**: Consider offering employee wellness initiatives, such as employee assistance programs (EAPs) or stress management workshops, to help employees manage work-related stress and improve their overall well-being.

By addressing these individual risk factors and implementing these recommendations, the organization can proactively work to reduce the likelihood of attrition and improve the employee's overall experience.

# 5- Analysis: Qualitative & Quantitative Results

### Quantitative Analysis 

The generated outputs were evaluated based on several important criteria to assess the effectiveness of each prompt template in supporting the employee attrition prediction system.

**Relevance**

Relevance measures whether the generated explanation aligns with the predicted attrition outcome and the employee features provided in the input.

- T1 generally produced relevant explanations but remained broad and generic
- T2 improved relevance by explicitly identifying risk factors related to attrition
- T3 focused only on the most important factors, which improved directness but reduced depth
- T4 showed the highest relevance because it consistently connected specific employee characteristics, such as overtime and job satisfaction, to the predicted attrition outcome

Overall, all templates were capable of generating relevant outputs, but T4 demonstrated the strongest alignment with the employee context and prediction.

**Detail & Completeness**

This criterion evaluates whether the generated outputs provide sufficient information and explanation.

- T1 generated short explanations with limited detail
- T2 provided more complete outputs through structured analysis of risk factors
- T3 intentionally reduced detail in favor of concise summaries for managers
- T4 produced the most complete responses by combining explanation, reasoning, and actionable recommendations

T4 provided the richest information and the most comprehensive analysis among all templates.

**Clarity & Readability**

This criterion evaluates whether the generated explanations can be easily understood by non-technical users.

- T1 and T3 produced the clearest outputs due to their simple language and short sentences
- T2 remained readable while introducing more structure and analytical detail
- T4 generated longer responses, which slightly reduced readability, but the explanations remained understandable and well-organized

Overall, T3 achieved the highest readability, while T4 balanced readability with greater informational value.

**Personalization**

Personalization measures how well the generated response reflects the specific employee context and individual features.

- T1 produced mostly generic explanations with little personalization
- T2 referenced employee factors but still remained relatively general
- T3 focused on high-level summaries and included limited personalization
- T4 demonstrated the strongest personalization by directly referencing employee-specific attributes and generating tailored recommendations based on those features

T4 clearly outperformed the other templates in personalization and contextual awareness.


**Safety & Factual Accuracy**

This criterion evaluates whether the generated outputs avoid unsupported assumptions or hallucinated information.

- T1 occasionally produced vague statements due to its open-ended structure
- T2 improved factual consistency through structured guidance
- T3 reduced hallucination risk by generating shorter and simpler outputs
- T4 minimized unsupported assumptions by explicitly instructing the model to rely only on the provided employee data

Although minor variations may occur due to the generative nature of the model, all templates generally maintained acceptable factual consistency. T4 showed the best balance between detail and controlled reasoning.

### Quantitative Analysis

The four prompt templates were compared using response length and readability. 

**Response Length**

Response length was evaluated using the generated word counts from the testing outputs.

T1 (Basic Explanation) produced responses ranging from 214 to 283 words
T2 (Structured HR Analysis) generated responses between 258 and 276 words
T3 (Manager-Friendly Explanation) produced the longest responses overall, ranging from 282 to 300 words
T4 (Personalized Retention Advice) generated responses between 249 and 267 words

Although T3 was intended to provide concise manager-friendly explanations, the generated outputs were unexpectedly longer than the other templates because the model produced additional explanations and recommendations. This demonstrates that actual LLM behavior may differ from the intended prompt design.

Overall, response length alone did not strongly indicate output quality, since longer responses were not always more useful or more personalized.

**Readability**

Readability was evaluated using the Flesch Reading Ease score, where higher scores indicate easier-to-read text and lower scores indicate more complex writing.

The average readability scores for the templates were:

In [22]:
import re
import textstat

def clean_text(text):
    text = re.sub(r"\*\*", "", str(text))  # remove markdown bold
    return text

results_df["Clean_Output"] = results_df["Output"].apply(clean_text)

results_df["Flesch_Reading_Ease"] = results_df["Clean_Output"].apply(
    textstat.flesch_reading_ease
)

results_df[["Template", "Case", "Flesch_Reading_Ease"]]

                            Template    Case  Flesch_Reading_Ease
0               T1_Basic_Explanation  Case 1            35.335282
1               T1_Basic_Explanation  Case 2            34.724866
2               T1_Basic_Explanation  Case 3            40.002174
3          T2_Structured_HR_Analysis  Case 1           -17.152535
4          T2_Structured_HR_Analysis  Case 2            29.502285
5          T2_Structured_HR_Analysis  Case 3            26.415801
6    T3_Manager_Friendly_Explanation  Case 1            45.666530
7    T3_Manager_Friendly_Explanation  Case 2            49.770658
8    T3_Manager_Friendly_Explanation  Case 3            51.474090
9   T4_Personalized_Retention_Advice  Case 1            34.358520
10  T4_Personalized_Retention_Advice  Case 2            25.488252
11  T4_Personalized_Retention_Advice  Case 3            18.321919

In [23]:
# Average readability score per template
readability_summary = results_df.groupby("Template")[
    "Flesch_Reading_Ease"
].mean().reset_index()

readability_summary

                           Template  Flesch_Reading_Ease
0              T1_Basic_Explanation            36.687441
1         T2_Structured_HR_Analysis            12.921850
2   T3_Manager_Friendly_Explanation            48.970426
3  T4_Personalized_Retention_Advice            26.056230

The results show that T3 achieved the highest readability score. This is consistent with its conversational and manager-friendly writing style, which used simpler explanations and more accessible language. T1 also maintained relatively good readability due to its straightforward explanations.

In contrast, T2 and T4 produced lower readability scores because they contained more detailed HR analysis, structured reasoning, and longer explanations.
Overall, the results demonstrate a trade-off between readability and informational depth. Templates that produced more detailed and analytical explanations tended to reduce readability, while simpler templates improved accessibility for non-technical users.

# 6- Best Prompt Selection & Justification
 Based on the quantitative and qualitative evaluation, Template 4 (T4 – Personalized Retention Advice) we selected as the best performing prompt template for integration into the final system.

T4 consistently generated the most detailed, personalized, and actionable outputs among all templates. Unlike the other templates, T4 explicitly connected employee-specific factors such as job satisfaction, work-life balance, overtime, tenure, and salary to attrition risk and retention strategies. The generated responses also included practical HR recommendations, making the outputs more useful for real-world decision-making scenarios.

The evaluation showed that:

- T1 performed well in simplicity and accessibility but lacked personalization and depth
- T2 improved structure and analytical reasoning but sometimes produced repetitive outputs
- T3 achieved the highest readability and conversational clarity but sacrificed analytical depth
- T4 provided the strongest balance between relevance, personalization, HR alignment, and practical usefulness

Although T4 produced lower readability scores compared to T1 and T3, this was expected because the template generated more detailed explanations and richer recommendations. The increased complexity was considered acceptable since the target users include HR professionals and organizational decision-makers who require deeper analysis rather than very short summaries.

Overall, T4 demonstrated the highest practical value and was selected as the most suitable template for deployment in the final employee attrition explanation system.

# 7- Integration Plan for Final System

## Overview

The final system integrates three components built across Phase 1 and Phase 2 into a unified HR decision-support pipeline. Each component adds a distinct layer of intelligence to the employee attrition analysis.

## System Pipeline

1- The employee's HR data is collected as input.

2- The Logistic Regression model (Phase 1) predicts whether the employee is likely to leave (Yes/No) along with a probability score.

3- DBSCAN assigns the employee to a behavioral cluster: 0 = Typical Workforce, 1 = Senior High-Earner, 2 = Junior Low-Earner, or -1 for atypical profiles.

4- Template 4 takes the employee features, attrition prediction, and cluster context as input and generates a personalized explanation with retention recommendations.

5- The HR manager receives the full attrition report and reviews it before taking any action.

 **So in short:**

 Employee Features (HR Input) -> Phase 1 – Logistic Regression ->
 Phase 2A – DBSCAN Clustering -> Phase 2B – Template 4 (Personalized Retention Advice) -> HR Manager receives a complete, actionable attrition report




## How Clustering Enhances the Generative AI Output

Each DBSCAN cluster carries a distinct behavioral profile. By injecting the cluster context into the Template 4 prompt, the AI generates explanations that are more targeted and relevant to the specific group the employee belongs to.

| Cluster | Profile | Attrition Rate | Prompt Enhancement |
|---------|---------|----------------|--------------------|
| Cluster 0 | Typical Workforce | 16.7% | Standard personalized advice |
| Cluster 1 | Senior High-Earners | 0% | Focus on recognition and long-term engagement |
| Cluster 2 | Junior Low-Earners | 27.8% | Urgent retention language — critical risk flag |
| Noise (-1) | Atypical Profile | 16.2% | Caution note — recommendations may vary |

Without clustering, the GenAI prompt only knows the attrition prediction. With the cluster label, it also knows the employee's behavioral group, producing richer and more actionable advice.

## Deployment Approach

In a practical deployment:
1. HR enters the employee's features into the system

2. The Logistic Regression model produces an attrition prediction (Yes/No + probability)

3. DBSCAN assigns the employee to a cluster based on their feature profile

4. Template 4 receives the features, prediction, and cluster context and generates a personalized report

5. The HR manager reviews the report before taking any action

Human review is always required. The system supports decision-making but does not replace professional judgment.

# 8- Ethical Considerations & Limitations

Several ethical concerns must be considered when integrating Generative AI into employee attrition analysis systems.

**Bias and Fairness**

The generated outputs depend heavily on the underlying dataset and machine learning predictions. If the dataset contains bias, the generated explanations and recommendations may also reflect biased patterns.

**Hallucination Risk**

Generative AI models may occasionally produce unsupported assumptions or inaccurate explanations. Although prompt constraints were used to reduce hallucination, the risk cannot be completely eliminated.

**Privacy and Data Protection**

Employee-related information is sensitive and must be handled securely. Any real-world deployment should ensure proper protection of employee data and compliance with privacy regulations.

**Human Oversight**

The generated recommendations should support HR decision-making rather than replace human judgment. Final organizational decisions should always involve human review and professional evaluation.